site_name: Guia Lógica ESP

theme:
    name: material
    custom_dir: overrides
    language: es
    font: 
      text: Roboto   
    features:
      - content.code.copy 
      - navigation.tracking
      - navigation.top
      - navigation.footer
    logo: octicons-cpu-16
    #icon:
    #  previous: images/UI/rotate-left.png
    #  next: images/UI/rotate-right.png
    #  search: images/UI/search.png
    palette: 

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambia a modo obscuro

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Cambia a modo claro

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search:
      lang: es
  - roamlinks
  - offline
  # - optimize

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

nav:
  - Inicio: index.md
  - Como navegar en la guía: navegar-en-la-guia.md
  - ¿Que es la lógica?: 1-que-es-la-logica.md
  - La instrucción: 
    - Concepto de instrucción: 2-concepto-de-instruccion.md
  - Como escribir código: 
    - Como escribir código: 3-como-escribir-codigo.md
    - Trabajando con el editor visual: 3.1-trabajando-con-el-editor-visual.md
    - Trabjando con el editor manual: 3.2-trabajando-con-el-editor-manual.md
  - Limitaciones de la lógica: 4-limitaciones-de-la-logica.md
  - Variables y constantes: 5-variables-y-constantes.md
  - Tipos de datos: 6-tipos-de-datos.md
  - Instrucciones de operación: instrucciones-de-operacion.md
  - Instrucciones de control de unidades: instrucciones-de-control-de-unidades.md
  - Flujo de ejecución: flujo-de-ejecucion.md
  - Comentarios: comentarios.md
  - Contenido a agregar: contenido-a-agregar.md

