site_name: Guia Lógica ESP

theme:
    name: material
    custom_dir: overrides
    language: es
    font: 
      text: Roboto    
    logo:     
    palette: 

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambia a modo obscuro

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Cambia a modo claro

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search:
      lang: es
  - roamlinks
  - offline
  # - optimize

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

nav:
  - Guía Lógica Mindustry: index.md
  - Contenido a agregar: contenido-a-agregar.md
  - Como escribir código: como-escribir-codigo.md
  - Limitaciones de la lógica: limitaciones-de-la-logica.md
  - Variables y constantes: variables-y-constantes.md
  - Tipos de datos: tipos-de-datos.md
  - Comentarios: comentarios.md
